project:
  type: website
  output-dir: docs

website:
  title: "Do not read"
  navbar:
    right:
      - text: "About"
        href: "https://elrobin.github.io/"
    logo: images/privatesign.png
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

