project:
  type: website
  output-dir: docs

website:
  title: "Draft6_final3_rev_final.docx"
  navbar:
    right:
      - text: "About"
        href: "https://elrobin.github.io/"

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

